name: Render and test
description: 'Render and check alerts'
author: Scality
inputs:
  alert_file_path:
    description: path of the alert to render and test
    required: true
  test_file_path:
    description: path of the unit test file for alerts
    required: true
  alert_inputs:
    description: a string with the alert inputs in the form "namespace=tesla,service=falcon9"
    required: true
  github_token:
    description: Github secret token to pull alertgen tool
    required: true

runs:
  using: "composite"
  steps:
    - name: Pull alertgen tool
      shell: bash
      run: gh release download -R scality/action-prom-render-test -p 'alertgen' --skip-existing
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Set execute flag
      shell: bash
      run: chmod +x ./alertgen

    - name: Render alert
      shell: bash
      run: >
        ./alertgen ${{ inputs.alert_file_path }} -i ${{ inputs.alert_inputs }}
    - name: Test alert
      shell: bash
      run: |
        docker run --rm -t -v ${PWD}/:/tests/ --entrypoint=promtool prom/prometheus:v2.33.4 test rules /tests/${{ inputs.test_file_path }}
